spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://119.29.35.226:3306/petclinic?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: petclinic
        password: petclinic
